### ISSUE TITLE
Add a WITH- macro

### ISSUE THREAD

**Issue by phoe** [tdrhq/file-lock#1]
The manual `MAKE-FILE-LOCK` and `RELEASE-FILE-LOCK` with `UNWIND-PROTECT` can probably be abstracted away into a single `(WITH-FILE-LOCK (...) ...)` macro that abstracts it away. Would you consider adding it?

**Comment by tdrhq** [comment]
Fixing this right now

**Comment by tdrhq** [comment]
Done: https://github.com/tdrhq/file-lock/commit/d2e3a34ac849d5c038eb355e4b62cc2240b38375
